gripper:
  closed_position: 0.0
  joint_names:
  - gripper_left
  - gripper_right
  open_position: 0.04
name: dynamic_plant
objects:
- name: cube_1
  position:
  - 0.5
  - 0.0
  - 0.05
  properties:
    graspable: true
    size:
    - 0.05
    - 0.05
    - 0.05
  type: box
robot:
  base_link: base_link
  ee_link: end_effector
  model_path: hardware/urdf/robot.xml
  type: generic
