# Minimal Manipulation Plant Configuration
# This is a minimal example for quick testing

name: minimal_plant

robot:
  type: generic
  model_path: "hardware/urdf/robot.xml"
  base_link: "base_link"
  ee_link: "end_effector"

gripper:
  joint_names: ["gripper_left", "gripper_right"]
  open_position: 0.04
  closed_position: 0.0

objects:
  - name: test_cube
    type: box
    position: [0.5, 0.0, 0.05]
    properties:
      size: [0.05, 0.05, 0.05]
      graspable: true
